/*
 * Copyright (C) 2026 Open Source Robotics Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef GZ_SIM_PYTHON_COMPONENTPYBINDREGISTRY_HH_
#define GZ_SIM_PYTHON_COMPONENTPYBINDREGISTRY_HH_

#ifdef HAVE_PYBIND11

#include <pybind11/chrono.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include <functional>
#include <string>
#include <type_traits>

#include <gz/sim/components/Component.hh>
#include <gz/sim/EntityComponentManager.hh>
#include <gz/sim/Export.hh>
#include <gz/sim/Types.hh>
#include <gz/utils/ImplPtr.hh>

namespace gz
{
namespace sim
{
namespace python
{
/// \namespace gz::sim::python::detail
/// \brief Internal implementation details for Python component bindings.
/// These APIs are not intended for public use and should only be accessed
/// via the GZ_SIM_REGISTER_PYTHON_COMPONENT registration macro.
namespace detail
{
/// \brief Represents a component type registered in Gazebo for Python.
struct ComponentProxy
{
  std::string name;
  gz::sim::ComponentTypeId typeId{0};
};

/// \brief Registry for mapping C++ components to Python runtimes via pybind11.
///
/// \details This registry allows the Gazebo Entity Component Manager (ECM) to
/// translate C++ component data into Python objects dynamically at runtime. It
/// stores type-erased `Getter`, `Setter`, etc functions indexed by
/// `ComponentTypeId`.
///
/// ### Shared Library Memory Safety (The Queue Paradigm)
/// Static functions (like getters/setters generated by templates) reside in the
/// memory space of the plugin or translation unit that defined them. If Plugin
/// A unloads, its function pointers become dangling. If Plugin B also uses that
/// same component, we *must* use Plugin B's memory space.
///
/// To solve this, the registry mirrors Gazebo's `ComponentDescriptorQueue`.
/// Instead of a simple reference count, it maintains a **Double-Ended Queue
/// (`std::deque`) of Bindings** tracked by the loader's unique identity
/// (`uintptr_t`, usually the object address of the registration hook).
///
/// - **Registration**: When a plugin loads, it pushes its descriptors to the
/// `front()` of the queue. The system always uses the most recently loaded
/// valid pointer.
/// - **Teardown**: When a plugin unloads, its specific descriptors are
/// surgically removed from the queue. The system automatically falls back to
/// the next valid descriptor in the queue (if any), preventing segfaults.
class GZ_SIM_VISIBLE ComponentPybindRegistry
{
  /// \brief Get the singleton instance of the registry.
  /// \return Pointer to the singleton instance.
  public: static ComponentPybindRegistry *Instance();

  public: using GetterFn = std::function<pybind11::object(
      const gz::sim::EntityComponentManager &_ecm,
      const gz::sim::Entity &_entity)>;

  public: using SetterFn = std::function<bool(
      gz::sim::EntityComponentManager &_ecm,
      const gz::sim::Entity &_entity,
      const pybind11::object &_obj)>;

  public: using CreatorFn = std::function<bool(
      gz::sim::EntityComponentManager &_ecm,
      const gz::sim::Entity &_entity,
      const pybind11::object &_obj)>;

  public: using DefaultCreatorFn = std::function<bool(
      gz::sim::EntityComponentManager &_ecm,
      const gz::sim::Entity &_entity)>;

  /// \brief Register a python getter/setter/creator/default-creator tuple for
  /// a component type.
  /// \param[in] _typeId The component type ID.
  /// \param[in] _id Unique identity of the loader (usually address of
  /// registration object).
  /// \param[in] _getter The python getter function.
  /// \param[in] _setter The python setter function.
  /// \param[in] _creator The component creator function.
  /// \param[in] _defaultCreator The default component creator function.
  public: void Register(ComponentTypeId _typeId, uintptr_t _id,
                        GetterFn _getter, SetterFn _setter,
                        CreatorFn _creator,
                        DefaultCreatorFn _defaultCreator);

  /// \brief Unregister a python getter/setter pair for a component type.
  /// \param[in] _typeId The component type ID.
  /// \param[in] _id Unique identity of the loader to remove.
  public: void Unregister(ComponentTypeId _typeId, uintptr_t _id);

  /// \brief Get the active python getter for a component type.
  /// \param[in] _typeId The component type ID.
  /// \return The getter function, or nullptr if not found.
  public: GetterFn Getter(ComponentTypeId _typeId) const;

  /// \brief Get the active python setter for a component type.
  /// \param[in] _typeId The component type ID.
  /// \return The setter function, or nullptr if not found.
  public: SetterFn Setter(ComponentTypeId _typeId) const;

  /// \brief Get the active component creator for a component type.
  /// \param[in] _typeId The component type ID.
  /// \return The creator function, or nullptr if not found.
  public: CreatorFn Creator(ComponentTypeId _typeId) const;

  /// \brief Get the active default component creator for a component type.
  /// \param[in] _typeId The component type ID.
  /// \return The default creator function, or nullptr if not found.
  public: DefaultCreatorFn DefaultCreator(ComponentTypeId _typeId) const;

  /// \brief Check whether python bindings are registered for a component type.
  /// \param[in] _typeId The component type ID.
  /// \return True if at least one getter/setter pair is registered.
  public: bool HasBindings(ComponentTypeId _typeId) const;

  /// \brief Strip the "gz_sim_components." prefix from a component name if
  /// present.
  /// \param[in] _name Full component name.
  /// \return Component name without prefix.
  public: static std::string CleanName(const std::string &_name);

  /// \brief Constructor.
  private: ComponentPybindRegistry();

  /// \brief Destructor.
  private: ~ComponentPybindRegistry();

  /// \brief Friend class for singleton instantiation.
  private: friend class gz::utils::NeverDestroyed<ComponentPybindRegistry>;

  /// \internal
  /// \brief Pointer to private data.
  GZ_UTILS_UNIQUE_IMPL_PTR(dataPtr)
};

template <typename T>
struct AddPybindGetterSetter
{
  /// \brief Create a type-erased python getter for pybind11 capturing the
  /// component name.
  ///
  /// The name is captured by value. The registration macro passes a string
  /// literal owned by the registering translation unit, so a raw pointer
  /// would dangle once that DSO unloads -- which is precisely the situation
  /// the registry's descriptor queue exists to survive.
  ///
  /// \param[in] _name Name of the component.
  /// \return The getter function returning the component data cast to a python
  /// object (or ComponentProxy for NoData).
  static ComponentPybindRegistry::GetterFn CreateGetter(const char *_name)
  {
    return [name = std::string(_name)](
               const gz::sim::EntityComponentManager &_ecm,
               const gz::sim::Entity &_entity) -> pybind11::object
    {
      if constexpr (std::is_same_v<typename T::Type,
                                   gz::sim::components::NoData>)
      {
        if (_ecm.EntityHasComponentType(_entity, T::typeId))
        {
          return pybind11::cast(ComponentProxy{name, T::typeId});
        }
        return pybind11::none();
      }
      else
      {
        (void)name;
        auto comp = _ecm.Component<T>(_entity);
        if (comp)
        {
          // Return a snapshot, not an alias into ECM storage.
          //
          // `reference` would only produce a live reference for payloads
          // bound via pybind11::class_; payloads served by a specialized
          // type_caster (std::string, arithmetic, containers) ignore the
          // policy and copy. That split makes in-place mutation work for
          // some component types and silently fail for others.
          //
          // It is also unsafe: EnTT erase is swap-and-pop, so a retained
          // reference can alias another entity's component after a
          // component or entity removal.
          //
          // All writes go through EntityComponentManager::SetComponentData
          // (exposed as set_component_data), which is the only supported
          // mutation path.
          //
          // LIMITATION: this yields value semantics only for value-typed
          // payloads. A pointer-like payload (sdf::ElementPtr, or any
          // std::shared_ptr) is copied as a handle, so the Python object
          // aliases the component held in ECM storage. Mutating it writes
          // straight through and bypasses change detection.
          //
          // This is accepted rather than fixed. Such components carry
          // static configuration (an SDF element tree) that is read, not
          // written, from Python, and deep-copying it on every read would
          // cost far more than the access it serves.
          //
          // Treat any component whose data is a pointer as read-only from
          // Python. The aliasing also runs the other way: create_component
          // stores the caller's handle rather than a copy, so the object
          // passed in stays live.
          return pybind11::cast(comp->Data(),
                                pybind11::return_value_policy::copy);
        }
        return pybind11::none();
      }
    };
  }

  /// \brief Type-erased python setter for pybind11.
  ///
  /// Mirrors C++ SetComponentData<T>(): the new data is compared against the
  /// current data and written only if it differs.
  ///
  /// \param[in] _ecm The EntityComponentManager.
  /// \param[in] _entity The Entity to write to.
  /// \param[in] _obj The python object to cast and write.
  /// \return True if the component was created or modified.
  static bool Setter(gz::sim::EntityComponentManager &_ecm,
                     const gz::sim::Entity &_entity,
                     const pybind11::object &_obj)
  {
    if (!_ecm.HasEntity(_entity))
    {
      return false;
    }

    if constexpr (std::is_same_v<typename T::Type, gz::sim::components::NoData>)
    {
      if (!_obj.is_none())
      {
        throw pybind11::type_error(
            "Tag (NoData) components cannot accept data");
      }
      if (!_ecm.EntityHasComponentType(_entity, T::typeId))
      {
        return _ecm.CreateComponent(_entity, T()) != nullptr;
      }
      return false;
    }
    else
    {
      if (_obj.is_none())
      {
        throw pybind11::type_error(
            "Component cannot be created or updated without data");
      }
      try
      {
        auto data = pybind11::cast<typename T::Type>(_obj);
        return _ecm.SetComponentData<T>(_entity, data);
      }
      catch (const pybind11::cast_error &e)
      {
        throw pybind11::type_error(
            std::string("Failed to cast python object to component data type: ")
            + e.what());
      }
    }
  }

  /// \brief Type-erased python component creator for pybind11.
  ///
  /// Mirrors C++ CreateComponent<T>(): the component is created, or replaced
  /// if it already exists, and is marked changed either way. Creation does not
  /// go through Setter because  SetComponentData leaves an unchanged component
  /// untouched, whereas creation is always a write.
  ///
  /// \param[in] _ecm The EntityComponentManager.
  /// \param[in] _entity The Entity to attach to.
  /// \param[in] _obj The python object to cast and store.
  /// \return True if the component was created.
  static bool Creator(gz::sim::EntityComponentManager &_ecm,
                      const gz::sim::Entity &_entity,
                      const pybind11::object &_obj)
  {
    if (!_ecm.HasEntity(_entity))
    {
      return false;
    }

    if constexpr (std::is_same_v<typename T::Type, gz::sim::components::NoData>)
    {
      if (!_obj.is_none())
      {
        throw pybind11::type_error(
            "Tag (NoData) components cannot accept data");
      }
      return _ecm.CreateComponent(_entity, T()) != nullptr;
    }
    else
    {
      if (_obj.is_none())
      {
        throw pybind11::type_error(
            "Component cannot be created or updated without data");
      }
      try
      {
        auto data = pybind11::cast<typename T::Type>(_obj);
        return _ecm.CreateComponent(_entity, T(data)) != nullptr;
      }
      catch (const pybind11::cast_error &e)
      {
        throw pybind11::type_error(
            std::string("Failed to cast python object to component data type: ")
            + e.what());
      }
    }
  }

  /// \brief Create a default-constructed component on an entity.
  /// \param[in] _ecm The EntityComponentManager.
  /// \param[in] _entity The Entity to attach to.
  /// \return True if created successfully or already exists.
  static bool CreateDefault(gz::sim::EntityComponentManager &_ecm,
                            const gz::sim::Entity &_entity)
  {
    if (!_ecm.HasEntity(_entity))
    {
      return false;
    }
    if (!_ecm.EntityHasComponentType(_entity, T::typeId))
    {
      return _ecm.CreateComponent(_entity, T()) != nullptr;
    }
    return true;
  }

  /// \brief Register this type's getter/setter/creator/default-creator tuple.
  /// \param[in] _id Unique identity of the loader.
  /// \param[in] _name Name of the component.
  static void Register(uintptr_t _id, const char *_name)
  {
    ComponentPybindRegistry::Instance()->Register(
        T::typeId, _id, CreateGetter(_name), Setter, Creator, CreateDefault);
  }

  /// \brief Unregister this type's getter/setter pair.
  /// \param[in] _id Unique identity of the loader to remove.
  static void Unregister(uintptr_t _id)
  {
    ComponentPybindRegistry::Instance()->Unregister(T::typeId, _id);
  }
};

}  // namespace detail
}  // namespace python
}  // namespace sim
}  // namespace gz

#endif  // HAVE_PYBIND11

#endif  // GZ_SIM_PYTHON_COMPONENTPYBINDREGISTRY_HH_
