/*
 * Copyright (C) 2026 Open Source Robotics Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef GZ_SIM_PYTHON_COMPONENTPYBINDREGISTRY_HH_
#define GZ_SIM_PYTHON_COMPONENTPYBINDREGISTRY_HH_

#ifdef HAVE_PYBIND11

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include <functional>
#include <optional>
#include <string>
#include <type_traits>

#include <gz/sim/components/Component.hh>
#include <gz/sim/EntityComponentManager.hh>
#include <gz/sim/Export.hh>
#include <gz/sim/Types.hh>
#include <gz/utils/ImplPtr.hh>

namespace gz
{
namespace sim
{
namespace python
{
/// \brief Represents a component type registered in Gazebo for Python.
struct ComponentProxy
{
  std::string name;
  gz::sim::ComponentTypeId typeId{0};
};

/// \brief Registry for mapping C++ components to Python runtimes via pybind11.
///
/// \details This registry allows the Gazebo Entity Component Manager (ECM) to
/// translate C++ component data into Python objects dynamically at runtime. It
/// stores type-erased `Getter` and `Setter` functions indexed by
/// `ComponentTypeId`.
///
/// ### Shared Library Memory Safety (The Queue Paradigm)
/// Static functions (like getters/setters generated by templates) reside in the
/// memory space of the plugin or translation unit that defined them. If Plugin
/// A unloads, its function pointers become dangling. If Plugin B also uses that
/// same component, we *must* use Plugin B's memory space.
///
/// To solve this, the registry mirrors Gazebo's `ComponentDescriptorQueue`.
/// Instead of a simple reference count, it maintains a **Double-Ended Queue
/// (`std::deque`) of Bindings** tracked by the loader's unique identity
/// (`uintptr_t`, usually the object address of the registration hook).
///
/// - **Registration**: When a plugin loads, it pushes its descriptors to the
/// `front()` of the queue. The system always uses the most recently loaded
/// valid pointer.
/// - **Teardown**: When a plugin unloads, its specific descriptors are
/// surgically removed from the queue. The system automatically falls back to
/// the next valid descriptor in the queue (if any), preventing segfaults.
class GZ_SIM_VISIBLE ComponentPybindRegistry
{
  /// \brief Get the singleton instance of the registry.
  /// \return Pointer to the singleton instance.
  public: static ComponentPybindRegistry *Instance();

  public: using GetterFn = std::function<pybind11::object(
      const gz::sim::EntityComponentManager &_ecm,
      const gz::sim::Entity &_entity)>;

  public: using SetterFn = std::function<bool(
      gz::sim::EntityComponentManager &_ecm,
      const gz::sim::Entity &_entity,
      const pybind11::object &_obj,
      bool _compare)>;

  /// \brief Register a python getter/setter pair for a component type.
  /// \param[in] _typeId The component type ID.
  /// \param[in] _id Unique identity of the loader (usually address of
  /// registration object).
  /// \param[in] _getter The python getter function.
  /// \param[in] _setter The python setter function.
  public: void Register(ComponentTypeId _typeId, uintptr_t _id,
                        GetterFn _getter, SetterFn _setter);

  /// \brief Unregister a python getter/setter pair for a component type.
  /// \param[in] _typeId The component type ID.
  /// \param[in] _id Unique identity of the loader to remove.
  public: void Unregister(ComponentTypeId _typeId, uintptr_t _id);

  /// \brief Get the active python getter for a component type.
  /// \param[in] _typeId The component type ID.
  /// \return The getter function, or nullptr if not found.
  public: GetterFn Getter(ComponentTypeId _typeId) const;

  /// \brief Get the active python setter for a component type.
  /// \param[in] _typeId The component type ID.
  /// \return The setter function, or nullptr if not found.
  public: SetterFn Setter(ComponentTypeId _typeId) const;

  /// \brief Get the active python component proxy for a component type.
  /// \param[in] _typeId The component type ID.
  /// \return The component proxy, or std::nullopt if not registered.
  public: std::optional<ComponentProxy> Proxy(ComponentTypeId _typeId) const;

  /// \brief Check whether python bindings are registered for a component type.
  /// \param[in] _typeId The component type ID.
  /// \return True if at least one getter/setter pair is registered.
  public: bool HasBindings(ComponentTypeId _typeId) const;

  /// \brief Strip the "gz_sim_components." prefix from a component name if
  /// present.
  /// \param[in] _name Full component name.
  /// \return Component name without prefix.
  public: static std::string CleanName(const std::string &_name);

  /// \brief Constructor.
  private: ComponentPybindRegistry();

  /// \brief Destructor.
  private: ~ComponentPybindRegistry();

  /// \brief Friend class for singleton instantiation.
  private: friend class gz::utils::NeverDestroyed<ComponentPybindRegistry>;

  /// \internal
  /// \brief Pointer to private data.
  GZ_UTILS_UNIQUE_IMPL_PTR(dataPtr)
};

template <typename T>
struct AddPybindGetterSetter
{
  /// \brief Type-erased python getter for pybind11.
  /// \param[in] _ecm The EntityComponentManager.
  /// \param[in] _entity The Entity to read from.
  /// \return The component data cast to a python object (or ComponentProxy
  /// proxy for NoData).
  static pybind11::object Getter(const gz::sim::EntityComponentManager &_ecm,
                                 const gz::sim::Entity &_entity)
  {
    if constexpr (std::is_same_v<typename T::Type, gz::sim::components::NoData>)
    {
      if (_ecm.EntityHasComponentType(_entity, T::typeId))
      {
        auto proxy = ComponentPybindRegistry::Instance()->Proxy(T::typeId);
        return proxy ? pybind11::cast(*proxy) : pybind11::none();
      }
      return pybind11::none();
    }
    else
    {
      auto comp = _ecm.Component<T>(_entity);
      if (comp)
      {
        return pybind11::cast(comp->Data(),
                              pybind11::return_value_policy::reference);
      }
      return pybind11::none();
    }
  }

  /// \brief Type-erased python setter for pybind11.
  /// \param[in] _ecm The EntityComponentManager.
  /// \param[in] _entity The Entity to write to.
  /// \param[in] _obj The python object to cast and write.
  /// \param[in] _compare If true, performs an equality check to only update if
  /// changed.
  /// \return True if the component was created or modified.
  static bool Setter(gz::sim::EntityComponentManager &_ecm,
                     const gz::sim::Entity &_entity,
                     const pybind11::object &_obj,
                     bool _compare)
  {
    if (!_ecm.HasEntity(_entity))
    {
      return false;
    }

    if constexpr (std::is_same_v<typename T::Type, gz::sim::components::NoData>)
    {
      if (!_obj.is_none())
      {
        throw pybind11::type_error(
            "Tag (NoData) components cannot accept data");
      }
      (void)_compare;
      if (!_ecm.EntityHasComponentType(_entity, T::typeId))
      {
        return _ecm.CreateComponent(_entity, T()) != nullptr;
      }
      return true;
    }
    else
    {
      if (_obj.is_none())
      {
        throw pybind11::type_error(
            "Component cannot be created or updated without data");
      }
      try
      {
        auto data = pybind11::cast<typename T::Type>(_obj);
        if (_compare)
        {
          return _ecm.SetComponentData<T>(_entity, data);
        }

        T *comp = _ecm.Component<T>(_entity);
        if (nullptr == comp)
        {
          return _ecm.CreateComponent(_entity, T(data)) != nullptr;
        }
        comp->Data() = data;
        return true;
      }
      catch (const pybind11::cast_error &e)
      {
        throw pybind11::type_error(
            std::string("Failed to cast python object to component data type: ")
            + e.what());
      }
    }
  }

  /// \brief Register this type's getter/setter pair.
  /// \param[in] _id Unique identity of the loader.
  static void Register(uintptr_t _id)
  {
    ComponentPybindRegistry::Instance()->Register(
        T::typeId, _id, Getter, Setter);
  }

  /// \brief Unregister this type's getter/setter pair.
  /// \param[in] _id Unique identity of the loader to remove.
  static void Unregister(uintptr_t _id)
  {
    ComponentPybindRegistry::Instance()->Unregister(T::typeId, _id);
  }
};

}  // namespace python
}  // namespace sim
}  // namespace gz

#endif  // HAVE_PYBIND11

#endif  // GZ_SIM_PYTHON_COMPONENTPYBINDREGISTRY_HH_
