/*
 * Copyright (C) 2025 Open Source Robotics Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef GZ_SIM_DETAIL_COMPONENTPYBINDREGISTRY_HH_
#define GZ_SIM_DETAIL_COMPONENTPYBINDREGISTRY_HH_

#include <pybind11/pybind11.h>

#include <algorithm>
#include <deque>
#include <functional>
#include <unordered_map>
#include <iostream>

#include <gz/sim/EntityComponentManager.hh>
#include <gz/sim/Types.hh>
#include <gz/utils/NeverDestroyed.hh>

namespace gz
{
namespace sim
{
namespace python
{
/// \brief Registry for mapping C++ components to Python runtimes via pybind11.
///
/// \details This registry allows the Gazebo Entity Component Manager (ECM) to translate
/// C++ component data into Python objects dynamically at runtime. It stores type-erased
/// `Getter` and `Setter` functions indexed by `ComponentTypeId`.
///
/// ### Shared Library Memory Safety (The Queue Paradigm)
/// Static functions (like getters/setters generated by templates) reside in the memory 
/// space of the plugin or translation unit that defined them. If Plugin A unloads, its 
/// function pointers become dangling. If Plugin B also uses that same component, we *must* 
/// use Plugin B's memory space.
///
/// To solve this, the registry mirrors Gazebo's `ComponentDescriptorQueue`. Instead of
/// a simple reference count, it maintains a **Double-Ended Queue (`std::deque`) of Bindings**
/// tracked by the loader's unique identity (`uintptr_t`, usually the object address of the
/// registration hook).
///
/// - **Registration**: When a plugin loads, it pushes its descriptors to the `front()` 
///   of the queue. The system always uses the most recently loaded valid pointer.
/// - **Teardown**: When a plugin unloads, its specific descriptors are surgically 
///   removed from the queue. The system automatically falls back to the next valid 
///   descriptor in the queue (if any), preventing segfaults.
class ComponentPybindRegistry
{
  /// \brief Get the singleton instance of the registry.
  /// \return Pointer to the singleton instance.
  public: static ComponentPybindRegistry *Instance()
  {
    static gz::utils::NeverDestroyed<ComponentPybindRegistry> instance;
    return &instance.Access();
  }

  public: using GetterFn = std::function<pybind11::object(
      const gz::sim::EntityComponentManager &_ecm,
      const gz::sim::Entity &_entity)>;

  public: using SetterFn = std::function<void(gz::sim::EntityComponentManager &_ecm,
                                              const gz::sim::Entity &_entity,
                                              const pybind11::object &_obj)>;

  public: struct PybindDescriptor
  {
    uintptr_t id;
    GetterFn getter;
    SetterFn setter;
  };

  /// \brief Register a python getter/setter pair for a component type.
  /// \param[in] _typeId The component type ID.
  /// \param[in] _id Unique identity of the loader (usually address of registration object).
  /// \param[in] _getter The python getter function.
  /// \param[in] _setter The python setter function.
  public: void Register(ComponentTypeId _typeId, uintptr_t _id,
                        GetterFn _getter, SetterFn _setter)
  {
    this->gettersAndSetters[_typeId].push_front({_id, _getter, _setter});
  }

  /// \brief Unregister a python getter/setter pair for a component type.
  /// \param[in] _typeId The component type ID.
  /// \param[in] _id Unique identity of the loader to remove.
  public: void Unregister(ComponentTypeId _typeId, uintptr_t _id)
  {
    auto it = this->gettersAndSetters.find(_typeId);
    if (it != this->gettersAndSetters.end())
    {
      auto &queue = it->second;
      queue.erase(
          std::remove_if(queue.begin(), queue.end(),
                         [_id](const auto &_desc) { return _desc.id == _id; }),
          queue.end());

      if (queue.empty())
      {
        this->gettersAndSetters.erase(it);
      }
    }
  }

  /// \brief Get the active python getter for a component type.
  /// \param[in] _typeId The component type ID.
  /// \return The getter function, or nullptr if not found.
  public: GetterFn Getter(ComponentTypeId _typeId) const
  {
    auto it = this->gettersAndSetters.find(_typeId);
    if (it == this->gettersAndSetters.end() || it->second.empty())
      return nullptr;
    return it->second.front().getter;
  }

  /// \brief Get the active python setter for a component type.
  /// \param[in] _typeId The component type ID.
  /// \return The setter function, or nullptr if not found.
  public: SetterFn Setter(ComponentTypeId _typeId) const
  {
    auto it = this->gettersAndSetters.find(_typeId);
    if (it == this->gettersAndSetters.end() || it->second.empty())
      return nullptr;
    return it->second.front().setter;
  }

  private: std::unordered_map<ComponentTypeId, std::deque<PybindDescriptor>>
      gettersAndSetters;
};

template <typename T>
struct AddPybindGetterSetter
{
  /// \brief Type-erased python getter for pybind11.
  /// \param[in] _ecm The EntityComponentManager.
  /// \param[in] _entity The Entity to read from.
  /// \return The component data cast to a python object.
  static pybind11::object Getter(const gz::sim::EntityComponentManager &_ecm,
                                 const gz::sim::Entity &_entity)
  {
    auto comp = _ecm.Component<T>(_entity);
    if (comp)
    {
      return pybind11::cast(comp->Data());
    }
    return pybind11::none();
  }

  /// \brief Type-erased python setter for pybind11.
  /// \param[in] _ecm The EntityComponentManager.
  /// \param[in] _entity The Entity to write to.
  /// \param[in] _obj The python object to cast and write.
  static void Setter(gz::sim::EntityComponentManager &_ecm,
                     const gz::sim::Entity &_entity,
                     const pybind11::object &_obj)
  {
    if (_obj.is_none())
    {
      return;
    }
    try
    {
      auto data = pybind11::cast<typename T::Type>(_obj);
      T *comp = _ecm.Component<T>(_entity);

      if (nullptr == comp)
      {
        _ecm.CreateComponent(_entity, T(data));
        return;
      }
      comp->Data() = data;
    }
    catch (const pybind11::cast_error &e)
    {
      std::cerr << "Failed to cast python object to component data type: "
                << e.what() << std::endl;
    }
  }

  /// \brief Register this type's getter/setter pair.
  /// \param[in] _id Unique identity of the loader.
  static void Register(uintptr_t _id)
  {
    ComponentPybindRegistry::Instance()->Register(T::typeId, _id, Getter, Setter);
  }

  /// \brief Unregister this type's getter/setter pair.
  /// \param[in] _id Unique identity of the loader to remove.
  static void Unregister(uintptr_t _id)
  {
    ComponentPybindRegistry::Instance()->Unregister(T::typeId, _id);
  }
};

template <typename U>
struct AddPybindGetterSetter<
    gz::sim::components::Component<gz::sim::components::NoData, U>>
{
  static void Register(uintptr_t /*_id*/) {}
  static void Unregister(uintptr_t /*_id*/) {}
};

}  // namespace python
}  // namespace sim
}  // namespace gz

#endif
