FROM ubuntu:focal

RUN apt-get update \
 && apt-get install -y \
      sudo wget lsb-release gnupg curl \
 && apt-get clean

COPY docker/scripts/enable_stable.sh scripts/enable_stable.sh
RUN scripts/enable_stable.sh

COPY docker/scripts/install_common_deps.sh scripts/install_common_deps.sh
RUN scripts/install_common_deps.sh

COPY docker/scripts/enable_gcc8.sh scripts/enable_gcc8.sh
RUN scripts/enable_gcc8.sh
