#!/usr/bin/env python3
# Copyright (C) 2026 Open Source Robotics Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0

"""Generate an SDF world with N models laid out on a grid.

Two shapes are available via `--shape`:

  static_box (default)
    A simple 1 m cube flagged <static>true</static>. No joints,
    no dynamics — physics solving is essentially free, so this
    workload is dominated by ECS / scene-broadcaster work and is
    the right scenario for measuring the archetype-ECM speedup
    in a real `gz sim` run.

  double_pendulum
    A static base with a 2.2 m pole, an upper arm hinged at the
    pole top, and a lower arm hinged at the upper arm's tip.
    Mirrors the structure of
    examples/worlds/log_record_dbl_pendulum.sdf. Useful as a
    physics-saturated reference: most of the per-step time goes
    to the joint constraint solver, so ECS storage gains are
    invisible.

Models are arranged in a roughly-square grid on a single ground
plane, with the standard Physics + SceneBroadcaster +
UserCommands plugin set.

Typical use:

  # 1000 static boxes (no physics) — exposes ECS bottlenecks.
  ./tools/gen_grid_world.py -n 1000 -o /tmp/grid.sdf

  # 100 pendulums for a physics-bound comparison.
  ./tools/gen_grid_world.py -n 100 --shape double_pendulum \\
      --spacing 5 -o /tmp/grid.sdf

  gz sim -v 4 /tmp/grid.sdf
"""

import argparse
import math
import sys
import textwrap

# Header: physics + standard plugin trio + sun + ground plane.
_WORLD_HEADER = """\
<?xml version="1.0" ?>
<!--
  Auto-generated by tools/gen_double_pendulum_world.py.
  N pendulums = {n}, grid = {cols} x {rows}, spacing = {spacing} m.
-->
<sdf version="1.6">
  <world name="{world_name}">

    <physics name="1ms" type="ignored">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin
      filename="gz-sim-physics-system"
      name="gz::sim::systems::Physics">
    </plugin>
    <plugin
      filename="gz-sim-user-commands-system"
      name="gz::sim::systems::UserCommands">
    </plugin>
    <plugin
      filename="gz-sim-scene-broadcaster-system"
      name="gz::sim::systems::SceneBroadcaster">
    </plugin>

    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>1 1 1 1</diffuse>
      <specular>0.5 0.5 0.5 1</specular>
      <attenuation>
        <range>1000</range>
        <constant>0.9</constant>
        <linear>0.01</linear>
        <quadratic>0.001</quadratic>
      </attenuation>
      <direction>-0.5 0.1 -0.9</direction>
    </light>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>{ground_size} {ground_size}</size>
            </plane>
          </geometry>
        </collision>
        <visual name="visual">
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>{ground_size} {ground_size}</size>
            </plane>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
      </link>
    </model>
"""

_WORLD_FOOTER = """\

  </world>
</sdf>
"""

# Static 1 m cube. <static>true</static> tells gz-physics to skip
# integration entirely — no constraints, no contact resolution
# beyond the trivial ground-plane case. The grid becomes a near-
# zero-cost physics workload, so the per-step time is dominated by
# the ECS / scene-broadcaster path and the archetype speedup is
# observable in wall-clock numbers.
_STATIC_BOX_TEMPLATE = """\
    <model name="{name}">
      <pose>{x} {y} 0.5 0 0 0</pose>
      <static>true</static>
      <link name="link">
        <visual name="visual">
          <geometry>
            <box><size>1.0 1.0 1.0</size></box>
          </geometry>
          <material>
            <ambient>0.4 0.4 0.8 1</ambient>
            <diffuse>0.4 0.4 0.8 1</diffuse>
            <specular>0.5 0.5 0.5 1</specular>
          </material>
        </visual>
        <collision name="collision">
          <geometry>
            <box><size>1.0 1.0 1.0</size></box>
          </geometry>
        </collision>
      </link>
    </model>
"""

# A single double pendulum model. The model is wrapped in an outer
# <pose> by the caller to position it on the grid.
#
# Geometry follows examples/worlds/log_record_dbl_pendulum.sdf:
#   * 0.8-radius cylindrical base plate, 100 kg, with a 2.2 m pole.
#   * Upper arm: 0.9 m cylinder, hinged at the pole top.
#   * Lower arm: 0.9 m cylinder, hinged at the upper arm's tip.
# Initial conditions match the reference (upper arm pointing down at
# -90 deg, lower arm offset by another -30 deg) so each pendulum
# starts from a non-equilibrium pose and immediately swings.
_PENDULUM_TEMPLATE = """\
    <model name="{name}">
      <pose>{x} {y} 0 0 0 0</pose>
      <link name="base">
        <inertial>
          <mass>100</mass>
        </inertial>
        <visual name="vis_plate_on_ground">
          <pose>0 0 0.01 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.8</radius>
              <length>0.02</length>
            </cylinder>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
        <visual name="vis_pole">
          <pose>-0.275 0 1.1 0 0 0</pose>
          <geometry>
            <box><size>0.2 0.2 2.2</size></box>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
        <collision name="col_plate_on_ground">
          <pose>0 0 0.01 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.8</radius>
              <length>0.02</length>
            </cylinder>
          </geometry>
        </collision>
        <collision name="col_pole">
          <pose>-0.275 0 1.1 0 0 0</pose>
          <geometry>
            <box><size>0.2 0.2 2.2</size></box>
          </geometry>
        </collision>
      </link>

      <link name="upper_link">
        <pose>0 0 2.1 -1.5708 0 0</pose>
        <self_collide>0</self_collide>
        <inertial>
          <pose>0 0 0.5 0 0 0</pose>
        </inertial>
        <visual name="vis_upper_joint">
          <pose>-0.05 0 0 0 1.5708 0</pose>
          <geometry>
            <cylinder><radius>0.1</radius><length>0.3</length></cylinder>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
        <visual name="vis_lower_joint">
          <pose>0 0 1.0 0 1.5708 0</pose>
          <geometry>
            <cylinder><radius>0.1</radius><length>0.2</length></cylinder>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
        <visual name="vis_cylinder">
          <pose>0 0 0.5 0 0 0</pose>
          <geometry>
            <cylinder><radius>0.1</radius><length>0.9</length></cylinder>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
        <collision name="col_upper_joint">
          <pose>-0.05 0 0 0 1.5708 0</pose>
          <geometry>
            <cylinder><radius>0.1</radius><length>0.3</length></cylinder>
          </geometry>
        </collision>
        <collision name="col_lower_joint">
          <pose>0 0 1.0 0 1.5708 0</pose>
          <geometry>
            <cylinder><radius>0.1</radius><length>0.2</length></cylinder>
          </geometry>
        </collision>
        <collision name="col_cylinder">
          <pose>0 0 0.5 0 0 0</pose>
          <geometry>
            <cylinder><radius>0.1</radius><length>0.9</length></cylinder>
          </geometry>
        </collision>
      </link>

      <link name="lower_link">
        <pose>0.25 1.0 2.1 -2 0 0</pose>
        <self_collide>0</self_collide>
        <inertial>
          <pose>0 0 0.5 0 0 0</pose>
        </inertial>
        <visual name="vis_lower_joint">
          <pose>0 0 0 0 1.5708 0</pose>
          <geometry>
            <cylinder><radius>0.08</radius><length>0.3</length></cylinder>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
        <visual name="vis_cylinder">
          <pose>0 0 0.5 0 0 0</pose>
          <geometry>
            <cylinder><radius>0.1</radius><length>0.9</length></cylinder>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
        <collision name="col_lower_joint">
          <pose>0 0 0 0 1.5708 0</pose>
          <geometry>
            <cylinder><radius>0.08</radius><length>0.3</length></cylinder>
          </geometry>
        </collision>
        <collision name="col_cylinder">
          <pose>0 0 0.5 0 0 0</pose>
          <geometry>
            <cylinder><radius>0.1</radius><length>0.9</length></cylinder>
          </geometry>
        </collision>
      </link>

      <joint name="upper_joint" type="revolute">
        <parent>base</parent>
        <child>upper_link</child>
        <axis><xyz>1.0 0 0</xyz></axis>
      </joint>
      <joint name="lower_joint" type="revolute">
        <parent>upper_link</parent>
        <child>lower_link</child>
        <axis><xyz>1.0 0 0</xyz></axis>
      </joint>
    </model>
"""


def grid_dimensions(n):
    """Return (cols, rows) for a roughly-square grid holding N items.

    cols = ceil(sqrt(N)), rows = ceil(N / cols). The last row may be
    partially filled.
    """
    cols = max(1, int(math.ceil(math.sqrt(n))))
    rows = max(1, int(math.ceil(n / cols)))
    return cols, rows


# Per-shape metadata: SDF template, model-name prefix, and a
# default per-cell spacing safe for that shape's footprint.
_SHAPES = {
    "static_box": {
        "template": _STATIC_BOX_TEMPLATE,
        "name_prefix": "static_box",
        "default_spacing": 2.0,
    },
    "double_pendulum": {
        "template": _PENDULUM_TEMPLATE,
        "name_prefix": "double_pendulum",
        "default_spacing": 4.0,
    },
}


def render_world(n, spacing, world_name, shape):
    """Build the full SDF world string for the chosen shape."""
    cols, rows = grid_dimensions(n)
    shape_info = _SHAPES[shape]

    # Center the grid on the world origin so the camera-default view
    # frames it nicely.
    x0 = -(cols - 1) * spacing / 2.0
    y0 = -(rows - 1) * spacing / 2.0

    # Ground plane sized to fully contain the grid plus a margin.
    ground_size = max(100, int(max(cols, rows) * spacing) + 20)

    out = [_WORLD_HEADER.format(
        n=n,
        cols=cols,
        rows=rows,
        spacing=spacing,
        world_name=world_name,
        ground_size=ground_size,
    )]

    for i in range(n):
        col = i % cols
        row = i // cols
        x = x0 + col * spacing
        y = y0 + row * spacing
        out.append(shape_info["template"].format(
            name=f"{shape_info['name_prefix']}_{i:04d}",
            x=f"{x:.4f}",
            y=f"{y:.4f}",
        ))

    out.append(_WORLD_FOOTER)
    return "".join(out)


def main():
    parser = argparse.ArgumentParser(
        description=textwrap.dedent(__doc__),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "-n", "--count", type=int, required=True,
        help="number of models to generate (>= 1)")
    parser.add_argument(
        "-o", "--output", type=str, default=None,
        help="output file path (default: stdout)")
    parser.add_argument(
        "--shape", choices=sorted(_SHAPES.keys()),
        default="static_box",
        help="model shape to generate at each grid cell (default: "
             "static_box)")
    parser.add_argument(
        "--spacing", type=float, default=None,
        help="grid spacing between model centers, in meters. "
             "Default depends on --shape: 2.0 m for static_box, "
             "4.0 m for double_pendulum.")
    parser.add_argument(
        "--world-name", type=str, default=None,
        help="SDF <world name=...>. Default: <shape>_grid_<count>.")
    args = parser.parse_args()

    if args.count < 1:
        parser.error("--count must be >= 1")
    spacing = (args.spacing if args.spacing is not None
               else _SHAPES[args.shape]["default_spacing"])
    if spacing <= 0:
        parser.error("--spacing must be positive")

    world_name = args.world_name or f"{args.shape}_grid_{args.count}"
    sdf = render_world(args.count, spacing, world_name, args.shape)

    if args.output:
        with open(args.output, "w") as f:
            f.write(sdf)
        cols, rows = grid_dimensions(args.count)
        print(
            f"Wrote {args.count} {args.shape} models "
            f"({cols}x{rows} grid, spacing {spacing} m) "
            f"to {args.output}",
            file=sys.stderr,
        )
    else:
        sys.stdout.write(sdf)


if __name__ == "__main__":
    main()
