#!/usr/bin/env python3
# Copyright (C) 2026 Open Source Robotics Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0

"""Generate an SDF world with N double pendulums on a grid.

Each pendulum mirrors the structure used by gz-sim's existing
double-pendulum example worlds (a static base with a 2.2 m pole, an
upper arm hinged at the pole top, and a lower arm hinged at the
upper arm's tip). The pendulums are arranged in a roughly-square
grid on a single ground plane, all simulated by the standard
Physics + SceneBroadcaster + UserCommands plugin set.

Typical use:

  # 25 pendulums, default 4 m spacing, write to stdout
  ./tools/gen_double_pendulum_world.py -n 25 > /tmp/grid.sdf

  # 100 pendulums, 5 m spacing, written to a file
  ./tools/gen_double_pendulum_world.py -n 100 --spacing 5 \\
      -o /tmp/grid.sdf

  gz sim -v 4 /tmp/grid.sdf
"""

import argparse
import math
import sys
import textwrap

# Header: physics + standard plugin trio + sun + ground plane.
_WORLD_HEADER = """\
<?xml version="1.0" ?>
<!--
  Auto-generated by tools/gen_double_pendulum_world.py.
  N pendulums = {n}, grid = {cols} x {rows}, spacing = {spacing} m.
-->
<sdf version="1.6">
  <world name="{world_name}">

    <physics name="1ms" type="ignored">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin
      filename="gz-sim-physics-system"
      name="gz::sim::systems::Physics">
    </plugin>
    <plugin
      filename="gz-sim-user-commands-system"
      name="gz::sim::systems::UserCommands">
    </plugin>
    <plugin
      filename="gz-sim-scene-broadcaster-system"
      name="gz::sim::systems::SceneBroadcaster">
    </plugin>

    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>1 1 1 1</diffuse>
      <specular>0.5 0.5 0.5 1</specular>
      <attenuation>
        <range>1000</range>
        <constant>0.9</constant>
        <linear>0.01</linear>
        <quadratic>0.001</quadratic>
      </attenuation>
      <direction>-0.5 0.1 -0.9</direction>
    </light>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>{ground_size} {ground_size}</size>
            </plane>
          </geometry>
        </collision>
        <visual name="visual">
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>{ground_size} {ground_size}</size>
            </plane>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
      </link>
    </model>
"""

_WORLD_FOOTER = """\

  </world>
</sdf>
"""

# A single double pendulum model. The model is wrapped in an outer
# <pose> by the caller to position it on the grid.
#
# Geometry follows examples/worlds/log_record_dbl_pendulum.sdf:
#   * 0.8-radius cylindrical base plate, 100 kg, with a 2.2 m pole.
#   * Upper arm: 0.9 m cylinder, hinged at the pole top.
#   * Lower arm: 0.9 m cylinder, hinged at the upper arm's tip.
# Initial conditions match the reference (upper arm pointing down at
# -90 deg, lower arm offset by another -30 deg) so each pendulum
# starts from a non-equilibrium pose and immediately swings.
_PENDULUM_TEMPLATE = """\
    <model name="{name}">
      <pose>{x} {y} 0 0 0 0</pose>
      <link name="base">
        <inertial>
          <mass>100</mass>
        </inertial>
        <visual name="vis_plate_on_ground">
          <pose>0 0 0.01 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.8</radius>
              <length>0.02</length>
            </cylinder>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
        <visual name="vis_pole">
          <pose>-0.275 0 1.1 0 0 0</pose>
          <geometry>
            <box><size>0.2 0.2 2.2</size></box>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
        <collision name="col_plate_on_ground">
          <pose>0 0 0.01 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.8</radius>
              <length>0.02</length>
            </cylinder>
          </geometry>
        </collision>
        <collision name="col_pole">
          <pose>-0.275 0 1.1 0 0 0</pose>
          <geometry>
            <box><size>0.2 0.2 2.2</size></box>
          </geometry>
        </collision>
      </link>

      <link name="upper_link">
        <pose>0 0 2.1 -1.5708 0 0</pose>
        <self_collide>0</self_collide>
        <inertial>
          <pose>0 0 0.5 0 0 0</pose>
        </inertial>
        <visual name="vis_upper_joint">
          <pose>-0.05 0 0 0 1.5708 0</pose>
          <geometry>
            <cylinder><radius>0.1</radius><length>0.3</length></cylinder>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
        <visual name="vis_lower_joint">
          <pose>0 0 1.0 0 1.5708 0</pose>
          <geometry>
            <cylinder><radius>0.1</radius><length>0.2</length></cylinder>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
        <visual name="vis_cylinder">
          <pose>0 0 0.5 0 0 0</pose>
          <geometry>
            <cylinder><radius>0.1</radius><length>0.9</length></cylinder>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
        <collision name="col_upper_joint">
          <pose>-0.05 0 0 0 1.5708 0</pose>
          <geometry>
            <cylinder><radius>0.1</radius><length>0.3</length></cylinder>
          </geometry>
        </collision>
        <collision name="col_lower_joint">
          <pose>0 0 1.0 0 1.5708 0</pose>
          <geometry>
            <cylinder><radius>0.1</radius><length>0.2</length></cylinder>
          </geometry>
        </collision>
        <collision name="col_cylinder">
          <pose>0 0 0.5 0 0 0</pose>
          <geometry>
            <cylinder><radius>0.1</radius><length>0.9</length></cylinder>
          </geometry>
        </collision>
      </link>

      <link name="lower_link">
        <pose>0.25 1.0 2.1 -2 0 0</pose>
        <self_collide>0</self_collide>
        <inertial>
          <pose>0 0 0.5 0 0 0</pose>
        </inertial>
        <visual name="vis_lower_joint">
          <pose>0 0 0 0 1.5708 0</pose>
          <geometry>
            <cylinder><radius>0.08</radius><length>0.3</length></cylinder>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
        <visual name="vis_cylinder">
          <pose>0 0 0.5 0 0 0</pose>
          <geometry>
            <cylinder><radius>0.1</radius><length>0.9</length></cylinder>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
        <collision name="col_lower_joint">
          <pose>0 0 0 0 1.5708 0</pose>
          <geometry>
            <cylinder><radius>0.08</radius><length>0.3</length></cylinder>
          </geometry>
        </collision>
        <collision name="col_cylinder">
          <pose>0 0 0.5 0 0 0</pose>
          <geometry>
            <cylinder><radius>0.1</radius><length>0.9</length></cylinder>
          </geometry>
        </collision>
      </link>

      <joint name="upper_joint" type="revolute">
        <parent>base</parent>
        <child>upper_link</child>
        <axis><xyz>1.0 0 0</xyz></axis>
      </joint>
      <joint name="lower_joint" type="revolute">
        <parent>upper_link</parent>
        <child>lower_link</child>
        <axis><xyz>1.0 0 0</xyz></axis>
      </joint>
    </model>
"""


def grid_dimensions(n):
    """Return (cols, rows) for a roughly-square grid holding N items.

    cols = ceil(sqrt(N)), rows = ceil(N / cols). The last row may be
    partially filled.
    """
    cols = max(1, int(math.ceil(math.sqrt(n))))
    rows = max(1, int(math.ceil(n / cols)))
    return cols, rows


def render_world(n, spacing, world_name):
    """Build the full SDF world string."""
    cols, rows = grid_dimensions(n)

    # Center the grid on the world origin so the camera-default view
    # frames it nicely. Each pendulum's footprint is ~1.6 m wide
    # (base diameter); spacing should be larger than that to avoid
    # collisions or visual overlap.
    x0 = -(cols - 1) * spacing / 2.0
    y0 = -(rows - 1) * spacing / 2.0

    # Ground plane sized to fully contain the grid plus a margin.
    ground_size = max(100, int(max(cols, rows) * spacing) + 20)

    out = [_WORLD_HEADER.format(
        n=n,
        cols=cols,
        rows=rows,
        spacing=spacing,
        world_name=world_name,
        ground_size=ground_size,
    )]

    for i in range(n):
        col = i % cols
        row = i // cols
        x = x0 + col * spacing
        y = y0 + row * spacing
        out.append(_PENDULUM_TEMPLATE.format(
            name=f"double_pendulum_{i:04d}",
            x=f"{x:.4f}",
            y=f"{y:.4f}",
        ))

    out.append(_WORLD_FOOTER)
    return "".join(out)


def main():
    parser = argparse.ArgumentParser(
        description=textwrap.dedent(__doc__),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "-n", "--count", type=int, required=True,
        help="number of double pendulums to generate (>= 1)")
    parser.add_argument(
        "-o", "--output", type=str, default=None,
        help="output file path (default: stdout)")
    parser.add_argument(
        "--spacing", type=float, default=4.0,
        help="grid spacing between pendulum centers, in meters "
             "(default: 4.0). Each pendulum's base is 1.6 m across, so "
             "values below ~2.5 risk overlap.")
    parser.add_argument(
        "--world-name", type=str, default=None,
        help="SDF <world name=...>. Default: "
             "double_pendulum_grid_<count>.")
    args = parser.parse_args()

    if args.count < 1:
        parser.error("--count must be >= 1")
    if args.spacing <= 0:
        parser.error("--spacing must be positive")

    world_name = (args.world_name
                  or f"double_pendulum_grid_{args.count}")
    sdf = render_world(args.count, args.spacing, world_name)

    if args.output:
        with open(args.output, "w") as f:
            f.write(sdf)
        cols, rows = grid_dimensions(args.count)
        print(
            f"Wrote {args.count} pendulums ({cols}x{rows} grid, "
            f"spacing {args.spacing} m) to {args.output}",
            file=sys.stderr,
        )
    else:
        sys.stdout.write(sdf)


if __name__ == "__main__":
    main()
