name: Bazel CI
on:
  pull_request:
  push:
    branches:
      - 'gz-sim[1-9]?[0-9]'
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: bazel-contrib/.github/.github/workflows/bazel.yaml@v7.7.0
    with:
      # Note: Specifying bazel_versions overrides the default fallback behavior
      # (which would otherwise test .bazelversion and 8.0.0). All desired versions
      # (including the one in .bazelversion) must be listed here explicitly.
      # We add bazel 7.x since that is still supported on Jetty releases.
      bazel_versions: |
        [
          "7.x",
          "8.x",
          "9.x"
        ]
      folders: |
        [
          "."
        ]
      exclude: |
        [
          {"folder": ".", "bzlmodEnabled": false}
        ]
      exclude_windows: true
      bazel_test_command: "bazel test --repo_env=CC=clang --repo_env=CXX=clang++ --test_output=errors //..."
