name: Bazel CI
on:
  pull_request:
  push:
    branches:
      - 'gz-sim[1-9]?[0-9]'
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: bazel-contrib/.github/.github/workflows/bazel.yaml@v7.7.0
    with:
      folders: |
        [
          "."
        ]
      exclude: |
        [
          {"folder": ".", "bzlmodEnabled": false}
        ]
      exclude_windows: true
      bazel_test_command: "bazel test --repo_env=CC=clang --repo_env=CXX=clang++ --test_output=errors //..."
