name: nightly docker image builds

on:
  push:
  schedule:
    - cron: '0 6 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - uses: actions/checkout@v4
        with:
          repository: gazebosim/gz-sim
          ref: gz-sim9
          path: src
      - name: build base image
        uses: docker/build-push-action@v6
        with:
          file: src/docker/Dockerfile.base
          context: src
          tags: gz-sim:base
          load: true
      - name: build nightly image
        uses: docker/build-push-action@v6
        with:
          file: src/docker/Dockerfile.nightly
          build-contexts: |
            gz-sim:base=docker-image://gz-sim:base
          context: src
